// import { Geist, Geist_Mono, Inter } from "next/font/google";
import { Urbanist } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";

const urbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"],
});

export const poppins = Poppins({
    subsets: ["latin"], // required
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // all weights
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${urbanist.className} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
                    <Navbar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
